### ISSUE TITLE
Update User Guide

### ISSUE THREAD

**Issue by cheongsiuhong** [AY1920S1-CS2103-F10-1/main#46]
In particular, update all the commands we are planning to implement.

**Comment by gabrielchao** [comment]
#42 

Elaborate and clarify the nature of:
- [ ] Medical Conditions
- [ ] Prescriptions
- [ ] Appointments vs. Visits (`appt begin` vs `visit begin`)
- [ ] Notes vs. Todos
- [ ] Visit notes vs. General notes
- [ ] Priority number
- [ ] Process for scheduling an appointment and attending it

Update parameters for:
- [ ] Section 6 Appointments
- [ ] Section 7 Visits
- [ ] Section 8 Todo Templates

General refinements:
- [ ] Section 11 Importing and Exporting
- [ ] Section 12 Notifications
