### ISSUE TITLE
Appointment management v1.2 increments

### ISSUE THREAD

**Issue by sandydays** [AY1920S1-CS2103-F10-1/main#65]
Part of #64 

Expected progress by v1.2:
- [x] Add class for appointments with the necessary fields and references to other classes
- [x] Add basic support for recurring appointments
- [ ] Add list method for appointments and consider how to display it. Consider where this list of appointments is going to be managed and if another class needed for it; implement accordingly
- [ ] Also consider if patient should have their own list of appointments as a field and implement accordingly
- [ ] Include add, edit, and delete methods for appointments, as well as parsing of these commands (such as the date and time, etc.)

**Comment by crazoter** [comment]
Milestone v1.2 has been reached.
