### ISSUE TITLE
Infinite recursion in Person.hashCode() and Visit.hashCode()

### ISSUE THREAD

**Issue by gabrielchao** [AY1920S1-CS2103-F10-1/main#84]
After updating my branch in #80 with master, I encountered a `StackOverflowError` when attempting to execute `undo` under certain circumstances. In essence there is infinite recursion caused by the following code changed in #75:

https://github.com/AY1920S1-CS2103-F10-1/main/blob/8a6ead53c6a6c3f9f28efaa1ec95faf6ca5bbe15/src/main/java/seedu/address/model/visit/Visit.java#L91-L95
https://github.com/AY1920S1-CS2103-F10-1/main/blob/8a6ead53c6a6c3f9f28efaa1ec95faf6ca5bbe15/src/main/java/seedu/address/model/person/Person.java#L135-L139

Since the `hashCode` methods of `Visit` and `Person` are defined in reference to the hash codes of each other, attempting to call `Visit.hashCode()`, `Person.hashCode()`, or by extension `AddressBook.hashCode()` would result in infinite recursion.

The following test reproduces this error:
```
@Test
public void hashCode_noError() {
    AddressBook typicalAddressBook = getTypicalAddressBook();
    typicalAddressBook.hashCode();
}
```

**Comment by crazoter** [comment]
Good catch, will fix now. Drop a PM in telegram next time if you want a faster response time :)

**Comment by gabrielchao** [comment]
Resolved, thanks.
