### ISSUE TITLE
Appointment management v1.3 increments

### ISSUE THREAD

**Issue by sandydays** [AY1920S1-CS2103-F10-1/main#97]
Part of #64

Expected progress by v1.3:

- [ ] Add list method for appointments and consider how to display it. Consider where this list of appointments is going to be managed and if another class needed for it; implement accordingly
- [ ] Include add, edit, and delete methods for appointments, as well as parsing of these commands (such as the date and time, etc.)
- [ ] Handle clashing appointments

**Comment by gabrielchao** [comment]
Just a heads up to update this issue as v1.3 has ended.
